version: '3.7'
services:
  iris1:
    build: .
    container_name: irisfhirtemplate1

    ports:
      # webserver/management portal port
      - "62773:52773"
      # superserver default port
      - "61773:1972"
    volumes:
      - ./Out:/ISC/Out
          
    environment:
    - TZ=JST-9
